# .streamlit/config.toml

[theme]
# 强制使用浅色主题
base = "light"
primaryColor = "#0078D7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"

[browser]
# 禁用收集使用统计
gatherUsageStats = false

[server]
# 服务器配置
headless = true
enableCORS = false
enableXsrfProtection = true
